App_House/urls.py
from django.urls import path
from App_House.views import *

app_name = 'App_House'

urlpatterns = [
    path('create-owner/', createOwner, name='createOwner'),
    path('open-lock/', lockOpen, name='lockOpen'),
    path('lock-close/', lockClose, name='lockClose'),
    path('inside/', insideHouse, name='insideHouse'),
    path('outside/', outsideHouse, name='outsideHouse'),
    path('alert/', alert, name='alert'),
    path('change-password/', change_password, name='change_password'),
]

house_security_webview/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from App_House.views import index


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name="index"),
    path('house/', include('App_House.urls')),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_House/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class HouseOwner(models.Model):
    name = models.CharField(max_length=40)
    password_1 = models.CharField(max_length=20)
    password_2 = models.CharField(max_length=20)
    unlock = models.BooleanField(default=False)
    attempt = models.IntegerField(default=3)

App_House/forms.py
from django import forms
from App_House.models import *

class CreateOwnerForm(forms.ModelForm):
    class Meta:
        model = HouseOwner
        fields = ('name', 'password_1', 'password_2',)
        labels = {
            'name': 'Name',
            'password_1': 'Password',
            'password_2': 'Confirm Password',
        }
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Enter your name'}),
            'password_1': forms.TextInput(attrs={'placeholder': 'Enter password', 'type': 'password'}),
            'password_2': forms.TextInput(attrs={'placeholder': 'Confirm your Password', 'type': 'password'}),
        }
        
class LockOpenForm(forms.ModelForm):
    class Meta:
        model = HouseOwner
        fields = ('password_1',)
        labels = {
            'password_1': 'Password',
        }
        widgets = {
            'password_1': forms.TextInput(attrs={'placeholder': 'Enter password', 'type': 'password'}),
        }

class ChangePasswordForm(forms.ModelForm):
    class Meta:
        model = HouseOwner
        fields = ('password_1', 'password_2',)
        labels = {
            'password_1': 'Password',
            'password_2': 'Confirm Password',
        }
        widgets = {
            'password_1': forms.TextInput(attrs={'placeholder': 'Enter new password', 'type': 'password'}),
            'password_2': forms.TextInput(attrs={'placeholder': 'Confirm new Password', 'type': 'password'}),
        }

App_House/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from App_House.models import HouseOwner
from App_House.forms import CreateOwnerForm, LockOpenForm, ChangePasswordForm

from django.contrib import messages


# Create your views here.

def index(request):
    return redirect('App_House:outsideHouse')

def createOwner(request):
    all_owner = HouseOwner.objects.all()
    if all_owner.exists():
        if all_owner[0].attempt <= 0:
            return redirect('App_House:alert')
        if len(all_owner) >= 1:
            messages.info(request,"Only 1 Profile can be create!")
            return redirect('App_House:outsideHouse')
    else:
        form = CreateOwnerForm()
        if request.method == 'POST':
            form = CreateOwnerForm(request.POST)
            if form.is_valid():
                if request.POST['password_1'] != request.POST['password_2']:
                    messages.warning(request,"Passwords did not match!")
                    form = CreateOwnerForm(request.POST)
                    return render(request, 'App_House/createOwner.html', context={'form': form})
                form.save()
                messages.success(request,"Lock Created Successfully!")
                return redirect('App_House:outsideHouse')
    return render(request, 'App_House/createOwner.html', context={'form': form})

def lockOpen(request):
    all_owner = HouseOwner.objects.all()
    
    if len(all_owner) == 0:
        messages.info(request,"Create a lock profile first!")
        return redirect('App_House:createOwner')
    if all_owner[0].attempt <= 0:
        messages.warning(request,"Your chance is finished!")
        return redirect('App_House:alert')
    owner = all_owner[0]
    if owner.unlock == True:
        messages.info(request,"Already unlocked!")
        return redirect('App_House:insideHouse')
    form = LockOpenForm()
    if request.method == 'POST':
        form = LockOpenForm(request.POST)
        if form.is_valid():
            if owner.password_1 == request.POST['password_1']:
                owner.unlock = True
                owner.attempt = 3
                owner.save()
                messages.success(request,"House unlocked successfull!")
                return redirect('App_House:insideHouse')
            else:
                messages.warning(request,"Wrong password!")
                form = LockOpenForm()
                owner.attempt -= 1
                owner.save()
            if owner.attempt <= 0:
                messages.warning(request,"Your chance has been finished!")
                return redirect('App_House:alert')
    attempt = owner.attempt
    return render(request, 'App_House/lockOpen.html', context={'form': form, 'attempt': attempt})


def lockClose(request):
    all_owner = HouseOwner.objects.all()
    if len(all_owner) == 0:
        messages.info(request,"Create a lock profile first!")
        return redirect('App_House:createOwner')
    if all_owner[0].attempt <= 0:
        return redirect('App_House:alert')
    owner = all_owner[0]
    owner.unlock = False
    owner.save()
    messages.success(request,"House has been locked!")
    return redirect('App_House:outsideHouse')


def insideHouse(request):
    all_owner = HouseOwner.objects.all()
    if len(all_owner) == 0:
        messages.info(request,"Create a lock profile first!")
        return redirect('App_House:createOwner')
    if all_owner[0].attempt <= 0:
        messages.success(request,"Can't enter to house!")
        return redirect('App_House:alert')
    if all_owner[0].unlock == False:
        messages.success(request,"House is lock!")
        return redirect('App_House:outsideHouse')
    return render(request, 'App_House/insideHouse.html')

def outsideHouse(request):
    all_owner = HouseOwner.objects.all()
    if len(all_owner) == 0:
        return redirect('App_House:createOwner')
    if all_owner[0].attempt <= 0:
        messages.warning(request,"You can't move right now!")
        return redirect('App_House:alert')
    if all_owner[0].unlock == True:
        messages.success(request,"Lock first to go outside!")
        return redirect('App_House:insideHouse')
    return render(request, 'App_House/outsideHouse.html')

def alert(request):
    all_owner = HouseOwner.objects.all()
    form = LockOpenForm()
    if len(all_owner) == 0:
        messages.info(request,"Create a lock profile first!")
        return redirect('App_House:createOwner')
    if all_owner[0].attempt != 0:
        messages.info(request,"You have chance to unlock!")
        return redirect('App_House:lockOpen')
    if request.method == 'POST':
        form = LockOpenForm(request.POST)
        if form.is_valid():
            if all_owner[0].password_1 == request.POST['password_1']:
                all_owner[0].attempt = 3
                all_owner[0].save()
                messages.success(request,"Alarm stopped!")
                return redirect('App_House:outsideHouse')
            form = LockOpenForm()
            messages.warning(request,"Wrong password!")
    return render(request, 'App_House/alert.html', context={'form': form})


def change_password(request):
    all_owner = HouseOwner.objects.all()
    if len(all_owner) == 0:
        messages.info(request,"Create a lock profile first!")
        return redirect('App_House:createOwner')
    if all_owner[0].attempt <= 0:
        messages.warning(request,"You can't move right now!")
        return redirect('App_House:alert')
    if all_owner[0].unlock == False:
        messages.warning(request,"Unlock first to change password!")
        return redirect('App_House:lockOpen')
    form = ChangePasswordForm()
    if request.method == 'POST':
        form = ChangePasswordForm(request.POST)
        if form.is_valid():
            if request.POST['password_1'] != request.POST['password_2']:
                messages.warning(request,"Password did not match!")
            else:
                messages.success(request,"Password changed!")
                all_owner[0].password_1 = request.POST['password_1']
                all_owner[0].password_2 = request.POST['password_2']
                all_owner[0].save()
                return redirect('App_House:lockClose')
    return render(request, 'App_House/changepass.html', context={'form': form})

templates/App_House/alert.html
{% extends "base.html" %} {% load crispy_forms_tags %} {% block title_block %}
Alarm {%endblock%} {%block body_block%}
<div class="parent alarm">
  <div class="inner-image">
    <h2>Alarm</h2>
    <form method="POST">
      <h4>Enter Correct Password To Stop Alarm</h4>
      {% csrf_token %} {{form|crispy}}
      <button type="button" id="togglePassword">
        <i class="fa-solid fa-eye"></i>
      </button>
      <button type="submit" class="btn btn-primary w-100">Stop Alarm</button>
    </form>
  </div>
  <img src="/media/alarm.jpeg" />
</div>
{%endblock%}

templates/App_House/changepass.html
{% extends "base.html" %} {% load crispy_forms_tags %} {% block title_block %}
Change Password {%endblock%} {%block body_block%}
<div class="parent">
  <div class="inner-image">
    <h3>Change password</h3>
    <form method="POST">
      {% csrf_token %} {{form|crispy}}
      <button type="button" id="togglePassword">
        <i class="fa-solid fa-eye"></i>
      </button>
      <button type="submit" class="btn btn-primary w-100">Change</button>
    </form>
  </div>
  <img src="/media/lock.jpg" />
  <a
    class="btn btn-info"
    style="position: fixed; top: 10px; right: 10px"
    href="{%url 'App_House:insideHouse'%}"
    >Go to house</a
  >
</div>
{%endblock%}

templates/App_House/createOwner.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title_block %} Create House Member {%endblock%}
{%block body_block%}
<div class="parent">
    <div class="inner-image pb-4">
        <h3>Create a family member profile</h3>
        <form method='POST'>
            {% csrf_token %}
            {{form|crispy}}
            <button type="button" id="togglePassword"><i class="fa-solid fa-eye"></i></button>
            <button type="submit" class="btn btn-primary w-100">Add a family member</button>
        </form>
    </div>
    <img src="/media/lock.jpg"/>
</div>
{%endblock%}

templates/App_House/insideHouse.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title_block %} Inside the house {%endblock%}
{%block body_block%}
<div class="parent">
    <div class="inner-image">
        <h3>Inside the house</h3>
        <a class="btn btn-dark" href="{%url 'App_House:lockClose'%}">Lock the house</a>
    </div>
    <img src="/media/inside.jpg"/>
    <a class="btn btn-warning" style="position: fixed;bottom: 10px;right: 10px;" href="{%url 'App_House:change_password'%}">Change password</a>
</div>
{%endblock%}

templates/App_House/lockClose.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title_block %} Lock {%endblock%}
{%block body_block%}
<h3>Lock</h3>
{%endblock%}

templates/App_House/lockOpen.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title_block %} Lock Open {%endblock%}
{%block body_block%}
<div class="parent">
    <div class="inner-image">
        <h3>Enter password to open the lock</h3>
        <p class="bg-dark text-light p-2">Attempt left: <span style="font-weight: 700;" {%if attempt == 1%}class="text-danger"{%elif attempt == 2%}class="text-warning"{%endif%}>{{attempt}}</span></p>
        <form method='POST'>
            {% csrf_token %}
            {{form|crispy}}
            <button type="button" id="togglePassword"><i class="fa-solid fa-eye"></i></button>
            <button type="submit" class="btn btn-primary w-100">Open</button>
        </form>
    </div>
    <img src="/media/lock.jpg"/>
</div>
{%endblock%}

templates/App_House/outsideHouse.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title_block %} Outside of the house {%endblock%}
{%block body_block%}
<div class="parent">
    <div class="inner-image">
        <h3>Outside of the house</h3>
        <a class="btn btn-info" href="{%url 'App_House:lockOpen'%}">Get into the house</a>
    </div>
    <img src="/media/outside.jpg"/>
</div>
{%endblock%}

templates/App_House/project_details.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
      integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <style></style>
    <title>Project Details</title>
  </head>
  <body>
    <div
      class="text-light w-100 h-100 d-flex flex-column align-items-center pt-4 pb-4"
      style="overflow: auto"
    >
        <div class="d-flex flex-column align-items-center border p-4">
            <h1>Project Details</h1>
            <h3 style="text-align: center;">Project Name: House Security System</h3>
            <h3 style="text-align: center;">Subject Name: Project Work - I</h3>
            <h3>Semester: 5th</h3>
            <h3>Shift: 2nd</h3>
            <h3>Session: 21-22</h3>
        </div>

      <h4 class="mt-4 border-bottom">Project Members</h4>

      <table class="table m-3" style="width: 90%">
        <thead>
          <tr>
            <th scope="col">Roll</th>
            <th scope="col">Name</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>616373</td>
            <td>Name</td>
          </tr>
          <tr>
            <td>616362</td>
            <td>Name</td>
          </tr>
          <tr>
            <td>616388</td>
            <td>Name</td>
          </tr>
          <tr>
            <td>616395</td>
            <td>Name</td>
          </tr>
          <tr>
            <td>616402</td>
            <td>Md Abdus Sabur</td>
          </tr>
          <tr>
            <td>616403</td>
            <td>Name</td>
          </tr>
          <tr>
            <td>616404</td>
            <td>Name</td>
          </tr>
          <tr>
            <td>515409</td>
            <td>Name</td>
          </tr>
          <tr>
            <td>639173</td>
            <td>Name</td>
          </tr>
          <tr>
            <td>676962</td>
            <td>Name</td>
          </tr>
        </tbody>
      </table>
    </div>

    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
  </body>
</html>